### ISSUE TITLE
Cloud9

### ISSUE THREAD

**Issue by Megamoneymeter** [aws-samples/serverless-coffee-workshop#10]
I'm trying to practice with the AWS Serverless-coffee-workshop and in the process of Launching the AWS CloudFormation template, it keeps rolling back with the error"User arn:aws:sts::066712572114:assumed-role/TeamRole/MasterKey does not exist" when it starts creating Cloud9. Please see attached. How do i fix this?
![serverless_coffee_shop](https://user-images.githubusercontent.com/36515308/173879626-e3c3db95-1601-4d75-ab64-279f125134c6.PNG)

**Comment by guikcd** [comment]
Removing the last line `OwnerArn` from the template.yaml file (you can get it from `Quick create stack` in the `Template url section` from https://workshop.serverlesscoffee.com/0-setup/1-self-hosted.html; url start with https://ee-assets-prod-us-east-1.s3.amazonaws.com/) and use it to create a new `serverless-workshop` CloudFormation stack with the fixed template help. Maybe my colleagues which maintain this repo will propose another solution.

**Comment by bls20AWS** [comment]
The workshop no longer uses Cloud9. Please use the new CFN  template with updated instructions
