### ISSUE TITLE
Configuration for the display app is total different than the workshop configuration

### ISSUE THREAD

**Issue by jerryliu-p** [aws-samples/serverless-coffee-workshop#13]
Hello, I've tried to deploy the display app and configure it. It seems like it's different from the workshop tutorial configuration. Please provide some instruction on how to configure the display app or maybe the code needs to be updated. Thank you!

![image](https://user-images.githubusercontent.com/109538860/189174433-90fd9b4d-c60f-4138-a1be-7076be56b4d0.png)

![image](https://user-images.githubusercontent.com/109538860/189174974-1e4a2305-ecee-4b79-ae8b-09a686ec2d63.png)

**Comment by bls20AWS** [comment]
The workshop front-ends are hosted externally and are in this repo as examples only.
If you follow the instructions here: https://workshop.serverlesscoffee.com/3-web-apps/3-frontends/1-displayapp.html you will see how to enter configure the web app.
