### ISSUE TITLE
Misleading cloudformation stack name

### ISSUE THREAD

**Issue by chong-aws** [aws-samples/serverless-coffee-workshop#16]
The statement "From the List of Stacks, select the core stack it should be named something like mod-67b03f2bcecc4faf." is quite misleading as the real name is "serverless-workshop" which is defined in setup section by following guide.

The statement can be found in https://workshop.serverlesscoffee.com/3-web-apps/3-frontends/1-displayapp.html

The stack name was defined in https://workshop.serverlesscoffee.com/0-setup/2-self-hosted.html

**Comment by bfreiberg** [comment]
This should be fixed now, please reopen if the issue persists
