### ISSUE TITLE
Inconsistency in heartbeat value in workflow wait for order

### ISSUE THREAD

**Issue by guikcd** [aws-samples/serverless-coffee-workshop#23]
In the building the workflow part 1b, wait for order section (https://workshop.serverlesscoffee.com/1b-workflow/6-waitfororder.html) in instructions/content/1b-workflow/6-WaitForOrder/_index.en.md the workshop mention using a heartbeat timeout to 300 but the screenshot mention 900 (https://workshop.serverlesscoffee.com/images/se-mod1-wait4c.png).

**Comment by bfreiberg** [comment]
Value should be correct now. Please reopen if you still encounter this issue
