### ISSUE TITLE
wrong image 

### ISSUE THREAD

**Issue by iut62elec** [aws-samples/serverless-coffee-workshop#29]
I think image [here](https://workshop.serverlesscoffee.com/4-advanced/order-processor-workflow/_index_en.html#:~:text=In%20the%20state%20machine%20view%20in%20the%20console%2C%20the%20Graph%20inspector%20shows%20the%20workflow%20path%20taken%20as%20a%20result%20of%20capacity%20being%20unavailable%3A
![Screen Shot 2022-11-28 at 12 53 17 PM](https://user-images.githubusercontent.com/7864200/204347280-c1299786-7726-4e4f-a062-b65e4ed76b32.png)
) is wrong and need to replace by attached

**Comment by bfreiberg** [comment]
Image was updated, closing now
