### ISSUE TITLE
Links to Frontend apps source are broken. 

### ISSUE THREAD

**Issue by dcheng** [aws-samples/serverless-coffee-workshop#37]
Hi, 

On this page: https://workshop.serverlesscoffee.com/3-web-apps/3-frontends/1-displayapp.html, the link pointing to the source code for the Display App does not lead anywhere. The same seems to be the case for the Customer App and the Barista App in their respective pages.

Please kindly fix. Thanks.

**Comment by bfreiberg** [comment]
The links are working now. Please reopen if you still encounter this issue
