### ISSUE TITLE
Where can I find the stack for front end like mod-67b03f2bcecc4faf. thx

### ISSUE THREAD

**Issue by testereg** [aws-samples/serverless-coffee-workshop#39]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/22107249/220249366-5ae9bd1a-94fa-4f2e-8ea1-8ba40a75a6e1.png">

**Comment by bls20AWS** [comment]
There is no front end stack, this is hosted externally. The workshop shows you how to configure the front ends to work with your stack
