### ISSUE TITLE
Counting Service

### ISSUE THREAD

**Issue by asunar** [aws-samples/serverless-coffee-workshop#5]
Just curious, what are the reasons behind creating a Counter service backed by dynamodb to increment order numbers sequentially?

**Comment by jbesw** [comment]
Hello! The service uses a UUID internally to track orders, but these aren't really human readable in a coffee shop context. We wanted customers and baristas to refer to a short, unique order (e.g. order number 10) when picking up their drinks. The counter service ensures each number is unique and incremented with each order. A EventBridge scheduled rule then resets this number to 0 every night. HTH!
