### ISSUE TITLE
Bug: Creating CF Stack Node Error

### ISSUE THREAD

**Issue by mknoth197** [aws-samples/serverless-coffee-workshop#53]
Was going thru the workshop and was creating the CF stack provided in the guide and the CF stack failed to spin the IaC due to a an outdated version of node not agreeing with the lambdas. Here is the error below being thrown on the console

```
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: b7849899-a2bc-407f-9b71-a040a2f6a3d2)" (RequestToken: 8d8360a1-e5c2-928c-0161-eaf40d461301, HandlerErrorCode: InvalidRequest)
```

Image:
<img width="1033" alt="image" src="https://github.com/aws-samples/serverless-coffee-workshop/assets/144064785/4c83c611-1829-445a-a576-f3da54c066c5">

**Comment by mknoth197** [comment]
Depending on if this is a breaking change or not, but the version of the lambdas should be bumped to avoid this error

[Lambda that failed first](https://github.com/aws-samples/serverless-coffee-workshop/blob/main/setup/template.yaml#L660)

**Comment by bfreiberg** [comment]
Hi @mknoth197 , thanks for your bug report. As you mentioned, the issue can be resolved for now by updating the runtime version of the Lambda functions to Node v16. 
An upgrade to Node v20 isn't as easy, as that version uses the AWS SDK v3 instead of v2. 

We are currently working on updating the functions to resolve this.

**Comment by mknoth197** [comment]
@bfreiberg , the CF template that is fetched from the Self Hosted part of the workshop is still leveraging v14

S3 link: https://ee-assets-prod-us-east-1.s3.amazonaws.com/modules/67b03f2bcecc4fafb15053897585b61f/v1/cloudformationvLatest.yml

![image](https://github.com/aws-samples/serverless-coffee-workshop/assets/144064785/747ac91f-bbaf-41b4-b861-ce395bc978cb)
> Photo of CF template that is loaded

![image](https://github.com/aws-samples/serverless-coffee-workshop/assets/144064785/980b46a6-838a-43ec-957b-a2ae15c50bf6)
> Error message

**Comment by bfreiberg** [comment]
Hi @mknoth197 , thanks for the additional information. I'll let you know once we have released an update

**Comment by bfreiberg** [comment]
Hi, the template has been updated and it should work again. Could you please test it again
