### ISSUE TITLE
Getting Access Denied when trying to load cloud formation template

### ISSUE THREAD

**Issue by gauravngandhi** [aws-samples/serverless-coffee-workshop#54]
When I try to create cloud formation stack the url provided
`https://ee-assets-prod-us-east-1.s3.amazonaws.com/modules/67b03f2bcecc4fafb15053897585b61f/v1/cloudformationvLatest.yml` seems to be not available. I am getting access denied

**Comment by bfreiberg** [comment]
Hi @gauravngandhi, thanks for reporting this issue. I'll check what is going on

**Comment by bfreiberg** [comment]
Hi, the template URL has been updated and it should work again. Could you please test it again

**Comment by gauravngandhi** [comment]
Works now, thank you!!!!
