### ISSUE TITLE
S3 access is not working

### ISSUE THREAD

**Issue by digitalnationcloud** [aws-samples/serverless-coffee-workshop#55]
Hi, I am trying to build this workshop and I get an error message when I want to deploy this in my own account
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

https://ee-assets-prod-us-east-1.s3.amazonaws.com/modules/67b03f2bcecc4fafb15053897585b61f/v1/cloudformationvLatest.yml

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A3K39VQW7W5R6GQQ</RequestId>
<HostId>
75+rllJOY5Bv71lCaUKRUFRQRW5rVCDYi05vIYJKHDsJyPVXv32Wn7OWdvOW9UlPIF6Qd15OBVs=
</HostId>
</Error>

**Comment by bfreiberg** [comment]
Hi, the template URL has been updated and it should work again. Could you please test it again

**Comment by digitalnationcloud** [comment]
Thank you!

It is working now.

 
Stefan

 
-----Original message-----

**Comment by digitalnationcloud** [comment]
Hi Ben, any idea why this API code is not working anymore please?

 
At this this step: https://workshop.serverlesscoffee.com/1-workflow/3-shopopen.html <https://workshop.serverlesscoffee.com/1-workflow/3-shopopen.html> 

 
this code:


{
  "TableName": "serverlesspresso-config-table",
  "Key": {
    "PK": {
      "S": "config"
    }
  }
}

 
is not accepted in the API Parameters:

 

 
 
I really appreciate your help.

 
Thank you!

 
Stefan

 
-----Original message-----

**Comment by bfreiberg** [comment]
Hi, could you please check the existing tables in DynamoDB? There might be an issue with the tables names

**Comment by digitalnationcloud** [comment]
Thanks Ben,

 
table's name are correct, can be something wrong with the code syntax ?

 

 
Stefan

 
-----Original message-----

**Comment by bfreiberg** [comment]
Could you please share what the exact error message is that you are seeing?

**Comment by digitalnationcloud** [comment]
In this step:
 https://workshop.serverlesscoffee.com/1-workflow/3-shopopen.html
 when I put my APi code in state function BatchGetItem:

{
  "TableName": "serverlesspresso-config-table",
  "Key": {
    "PK": {
      "S": "config"
    }
  }
}

I get this error:
 There are Amazon States Language errors in your state machine definition. Fix the errors to continue.
*	The field 'RequestItems' is required but was missing /States/BatchGetItem/Parameters 
 

 
 
Stefan

 
-----Original message-----

**Comment by bfreiberg** [comment]
Ah, please make sure to use `GetItem` instead of `BatchGetItem`. 

> Drag the DynamoDB GetItem action from the list to the empty state in the designer.

**Comment by digitalnationcloud** [comment]
Hi Ben, thank a lot, it was me choosing the wrong GetItem action name.

It is working now.

 
Stefan

 
-----Original message-----

**Comment by bfreiberg** [comment]
Great, happy to hear that it works now
