### ISSUE TITLE
An error occurred while executing the state 'Emit - Awaiting Completion TT'

### ISSUE THREAD

**Issue by hojololar** [aws-samples/serverless-coffee-workshop#56]
I am getting the error below while running the Lab. I have done it 3 times to make sure i am not making any mistakes and yet i get the same error 

An error occurred while executing the state 'Emit - Awaiting Completion TT' (entered at the event id #27). The JSONPath '$.detail.orderId' specified for the field 'orderId.$' could not be found in the input '{"orderNumber":"10"}'

I get it when runnig this part of the lab https://workshop.serverlesscoffee.com/1b-workflow/6-waitfororder.html

**Comment by hojololar** [comment]
Hi @bfreiberg 
thanks for the response.

In the walkthrough. the order number variable is set her https://workshop.serverlesscoffee.com/1b-workflow/5-ordernumber.html#:~:text=Check%20the%20box%20Transform%20result%20with%20ResultSelector.

while as part of the testing, the instruction asked to pass this payload hence i am not particularly sure where theres a mismatch in orderid and ordernumber

**Comment by hojololar** [comment]
I juts wanted to add that the previous step also generated an Order number as detailed here https://workshop.serverlesscoffee.com/1b-workflow/5-ordernumber.html#:~:text=Payload%20containing%20an-,orderNumber,-of%201.

**Comment by bfreiberg** [comment]
Can you please share the output of the proceeding step "Generate Order Number". It should have a field "detail":

```
"detail": {
    "orderId": "1",
    "userId": "testuser"
  }
```

It looks like you might have missed configuring the Output processing in a previous step (*"Add original input to output using ResultPath"*)

**Comment by hojololar** [comment]
<img width="1365" alt="Screenshot 2024-05-02 at 11 15 26 AM" src="https://github.com/aws-samples/serverless-coffee-workshop/assets/65510502/a1b55a4e-4b27-4e38-aef8-a3e376ac5297">
<img width="1468" alt="Screenshot 2024-05-02 at 11 12 49 AM" src="https://github.com/aws-samples/serverless-coffee-workshop/assets/65510502/312f178e-694d-454d-a43f-59f705a59201">
<img width="1470" alt="Screenshot 2024-05-02 at 11 17 16 AM" src="https://github.com/aws-samples/serverless-coffee-workshop/assets/65510502/c3863615-d059-4fbd-acfa-00d110194d62">
<img width="1455" alt="Screenshot 2024-05-02 at 11 18 14 AM" src="https://github.com/aws-samples/serverless-coffee-workshop/assets/65510502/5bb8d346-905e-4dfb-8c23-8c88bb771fff">
Sharing screenshots of the current config and output

**Comment by bfreiberg** [comment]
It looks like your missing the checkmark in "Output" for "Add original input to output using ResultPath" in the DynamoDB step. Compare the screenshot in the instructions (https://workshop.serverlesscoffee.com/1b-workflow/5-ordernumber.html#:~:text=Check%20the%20box%20Transform%20result%20with%20ResultSelector) to yours

**Comment by bfreiberg** [comment]
Great, happy to hear that it works now.
