### ISSUE TITLE
Update Lambda examples to use node 20.x

### ISSUE THREAD

**Issue by trivikr** [aws-samples/serverless-coffee-workshop#58]
### Is your feature request related to a problem? Please describe.

There are multiple samples which uses Lambda Node.js versions which are end-of-life
* nodejs16.x https://github.com/search?q=repo%3Aaws-samples%2Fserverless-coffee-workshop+%22Runtime%3A+nodejs16.x%22&type=code
  * Deprecation is on `Jun 12, 2024` and function create will be blocked on `Feb 28, 2025`
* nodejs14.x https://github.com/search?q=repo%3Aaws-samples%2Fserverless-coffee-workshop+%22Runtime%3A+nodejs14.x%22&type=code
  * Function create was blocked on `Jan 9, 2024`

Lambda Supported Runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### Describe the solution you'd like

Update Lambda examples to use node 20.x, which [was made available on Nov 15, 2023](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

### Describe alternatives you've considered
N/A

**Comment by bfreiberg** [comment]
Hi @trivikr , the runtime has been upgraded to nodejs20.x, for details see #63
